"""MarketAlert: one alert *object* generated by
src.market_intelligence.alert_engine -- durable, queryable history of
what the layer flagged, and when. Generation only; there is no
notification/delivery mechanism anywhere in this codebase (email,
push, webhook) -- an explicit, disclosed scope boundary for this
milestone.
"""

import enum
from datetime import datetime, timezone

from sqlalchemy import Column, DateTime, Enum, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from src.core.db.database import Base


class AlertType(str, enum.Enum):
    NEW_STRONG_BUY = "NEW_STRONG_BUY"
    RECOMMENDATION_UPGRADED = "RECOMMENDATION_UPGRADED"
    RECOMMENDATION_DOWNGRADED = "RECOMMENDATION_DOWNGRADED"
    CONFIDENCE_ABOVE_THRESHOLD = "CONFIDENCE_ABOVE_THRESHOLD"
    TARGET_REACHED = "TARGET_REACHED"
    RISK_SPIKE = "RISK_SPIKE"
    SECTOR_ROTATION = "SECTOR_ROTATION"


class AlertSeverity(str, enum.Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class MarketAlert(Base):
    __tablename__ = "market_alerts"

    id = Column(Integer, primary_key=True)
    scan_run_id = Column(Integer, ForeignKey("market_scan_runs.id"), nullable=True, index=True)
    alert_type = Column(Enum(AlertType), nullable=False, index=True)
    severity = Column(Enum(AlertSeverity), nullable=False)
    symbol = Column(String(16), nullable=True, index=True)
    sector = Column(String(128), nullable=True)
    message = Column(Text, nullable=False)
    generated_at = Column(DateTime(timezone=True), nullable=False, index=True)

    created_at = Column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        server_default=func.now(),
    )

    scan_run = relationship("MarketScanRun")

    def __repr__(self) -> str:
        return f"<MarketAlert alert_type={self.alert_type} symbol={self.symbol!r}>"
