"""add_tokens_invalid_before_to_users

Revision ID: 11c293dc10f5
Revises: ed8a7fde8f20
Create Date: 2026-07-25 19:29:04.710842

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "11c293dc10f5"
down_revision: Union[str, Sequence[str], None] = "ed8a7fde8f20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("tokens_invalid_before", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "tokens_invalid_before")
    # ### end Alembic commands ###
