"""add watchlist_news_alerts

Revision ID: 5126413133b2
Revises: e1a4c7f92b03
Create Date: 2026-08-18 04:34:44.245804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '5126413133b2'
down_revision: Union[str, Sequence[str], None] = 'e1a4c7f92b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_news_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('news_event_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', postgresql.ENUM('UPGRADE', 'DOWNGRADE', 'HIGH_RISK', 'MAJOR_OPPORTUNITY', name='portfolioalerttype', create_type=False), nullable=False),
    sa.Column('severity', postgresql.ENUM('INFO', 'WARNING', 'CRITICAL', name='alertseverity', create_type=False), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['news_event_id'], ['news_events.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['user_watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_news_alerts_alert_type'), 'watchlist_news_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_watchlist_news_alerts_generated_at'), 'watchlist_news_alerts', ['generated_at'], unique=False)
    op.create_index(op.f('ix_watchlist_news_alerts_news_event_id'), 'watchlist_news_alerts', ['news_event_id'], unique=False)
    op.create_index(op.f('ix_watchlist_news_alerts_symbol'), 'watchlist_news_alerts', ['symbol'], unique=False)
    op.create_index(op.f('ix_watchlist_news_alerts_watchlist_id'), 'watchlist_news_alerts', ['watchlist_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping several *pre-existing*
    # unique constraints on unrelated tables (confidence_calibration_models,
    # daily_intelligence_snapshots, market_scan_progress, news_events,
    # news_source_reliability, reflection_reports) -- these are naming
    # drift between the live schema and the current ORM models from
    # earlier migrations, not something this migration should touch.
    # Removed to keep this migration scoped to watchlist_news_alerts only.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_news_alerts_watchlist_id'), table_name='watchlist_news_alerts')
    op.drop_index(op.f('ix_watchlist_news_alerts_symbol'), table_name='watchlist_news_alerts')
    op.drop_index(op.f('ix_watchlist_news_alerts_news_event_id'), table_name='watchlist_news_alerts')
    op.drop_index(op.f('ix_watchlist_news_alerts_generated_at'), table_name='watchlist_news_alerts')
    op.drop_index(op.f('ix_watchlist_news_alerts_alert_type'), table_name='watchlist_news_alerts')
    op.drop_table('watchlist_news_alerts')
    # ### end Alembic commands ###
