"""add fundamental_snapshots table

Revision ID: a75a1f329294
Revises: b0d5a7f91ccb
Create Date: 2026-07-24 01:30:19.289244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a75a1f329294'
down_revision: Union[str, Sequence[str], None] = 'b0d5a7f91ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundamental_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.Enum('ANNUAL', 'QUARTERLY', name='periodtype'), nullable=False),
    sa.Column('fiscal_period_end', sa.Date(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('total_assets', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('total_liabilities', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('total_equity', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('current_assets', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('current_liabilities', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('inventory', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('cash_and_equivalents', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('shares_outstanding', sa.BigInteger(), nullable=False),
    sa.Column('eps', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('dividend_per_share', sa.Numeric(precision=12, scale=4), server_default='0', nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'period_type', 'fiscal_period_end', name='uq_fundamental_snapshot_identity')
    )
    op.create_index(op.f('ix_fundamental_snapshots_fiscal_period_end'), 'fundamental_snapshots', ['fiscal_period_end'], unique=False)
    op.create_index(op.f('ix_fundamental_snapshots_stock_id'), 'fundamental_snapshots', ['stock_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fundamental_snapshots_stock_id'), table_name='fundamental_snapshots')
    op.drop_index(op.f('ix_fundamental_snapshots_fiscal_period_end'), table_name='fundamental_snapshots')
    op.drop_table('fundamental_snapshots')
    # ### end Alembic commands ###
    # Not auto-generated: op.drop_table('fundamental_snapshots') above removes
    # the table but Postgres ENUM types are independent objects that outlive
    # their column, so the type must be dropped explicitly or a subsequent
    # upgrade fails with "type already exists" -- same issue 0001's
    # 'timeframe' ENUM had (M2.1).
    sa.Enum(name='periodtype').drop(op.get_bind(), checkfirst=True)
