"""add_ai_usage_and_reports

Revision ID: f45b2abf22f4
Revises: 1f72c3a21ad8
Create Date: 2026-07-25 20:10:56.937293

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f45b2abf22f4"
down_revision: Union[str, Sequence[str], None] = "1f72c3a21ad8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("feature", sa.String(length=100), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("SUCCESS", "FAILED", "TIMEOUT", name="airequeststatus"),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "estimated_cost_usd", sa.Numeric(precision=10, scale=6), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_requests_feature"), "ai_requests", ["feature"], unique=False
    )
    op.create_index(
        op.f("ix_ai_requests_user_id"), "ai_requests", ["user_id"], unique=False
    )
    op.create_table(
        "recommendation_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("recommendation", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column(
            "viewed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recommendation_history_symbol"),
        "recommendation_history",
        ["symbol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendation_history_user_id"),
        "recommendation_history",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "report_type",
            sa.Enum("DAILY", "SECTOR", "MONTHLY", "QUARTERLY", name="reporttype"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "GENERATING", "READY", "FAILED", name="reportstatus"),
            nullable=False,
        ),
        sa.Column("file_url", sa.String(length=500), nullable=True),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reports_user_id"), "reports", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reports_user_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(
        op.f("ix_recommendation_history_user_id"), table_name="recommendation_history"
    )
    op.drop_index(
        op.f("ix_recommendation_history_symbol"), table_name="recommendation_history"
    )
    op.drop_table("recommendation_history")
    op.drop_index(op.f("ix_ai_requests_user_id"), table_name="ai_requests")
    op.drop_index(op.f("ix_ai_requests_feature"), table_name="ai_requests")
    op.drop_table("ai_requests")
    # ### end Alembic commands ###
    sa.Enum(name="reportstatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="reporttype").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="airequeststatus").drop(op.get_bind(), checkfirst=True)
